### ISSUE TITLE
Possible error in the Opacity Regularization formula in the paper.

### ISSUE THREAD

**Issue by inrainbws** [SheldonTsui/GOF_NeurIPS2021#1]
First of all, thank you for sharing this brilliant work. I discrovered a possible erorr in the Opacity Regularization formula in the paper while trying to implement this algorithm. The problem is that the opacity term described in the paper approaches negative infinity. According to the definition of entropy, I think the formula should be something like

<img src="https://render.githubusercontent.com/render/math?math=-\sum \alpha \log_2(\alpha) %2B (1 - \alpha) \log_2(1-\alpha)">

**Comment by SheldonTsui** [comment]
Hi @yzhq97 . Thanks for your interest in our work. For the formulation of opacity regularization, the reviewers also query this. Actually, we here regard the entropy of the opacity as the negative log-likelihood of the Beta distribution following the setting in "Neural Volumes"(Section 7.3). Besides, we added 0.1 inside the log term in the implementation to avoid the infinity values.

**Comment by inrainbws** [comment]
Thanks for the clarification!
