### ISSUE TITLE
HI，I have some questions about the preprocess of CelebA dataset

### ISSUE THREAD

**Issue by wasdzzzzzz** [SheldonTsui/GOF_NeurIPS2021#3]
Congrats on this great work, and thanks a lot for open-sourcing the code!
In the paper, you mention that “we crop all images in CelebA from the top of the hair to the bottom of the chin as a pre-processing step.” Can you provide specific steps or code scripts for pre-processing methods？
Thanks a lot in advance.

**Comment by SheldonTsui** [comment]
@JJJLLLTTT This processing has already been included in the datasets.py. Please refer to https://github.com/SheldonTsui/GOF_NeurIPS2021/blob/1e85de85de45acde9b32c41268108b1d936cef03/datasets.py#L24
Note that, the CelebA dataset must be aligned in advance where the image size is 218 x 178.

**Comment by wasdzzzzzz** [comment]
> 

Thank you very much for your reply~
