### ISSUE TITLE
Additional Results on CARLA

### ISSUE THREAD

**Issue by wasdzzzzzz** [SheldonTsui/GOF_NeurIPS2021#4]
Congrats on this great work, and thanks a lot for open-sourcing the code!
I have some trouble with the Carla dataset. Where did you get the Carla dataset？I can‘t find the pi-gan’s Carla dataset. And it seems different from Graf's. Can you provide me with a link to download the Carla dataset in your paper?
Thanks a lot in advance.

**Comment by SheldonTsui** [comment]
@JJJLLLTTT Thanks for your interest in our work. I see no difference between the piGAN's CARLA dataset and the one used in GRAF. I just leverage the CARLA dataset from GRAF in our paper.

**Comment by wasdzzzzzz** [comment]
> @JJJLLLTTT Thanks for your interest in our work. I see no difference between the piGAN's CARLA dataset and the one used in GRAF. I just leverage the CARLA dataset from GRAF in our paper.

How many pictures did you use to calculate FID? And is the pi-gan model you tested provided by pi-gan github
?

**Comment by SheldonTsui** [comment]
Hi, @JJJLLLTTT 2048 images are used. We use the pi-GAN model trained by ourselves, not the provided version. Have you found anything abnormal?

**Comment by wasdzzzzzz** [comment]
> Hi, @JJJLLLTTT 2048 images are used. We use the pi-GAN model trained by ourselves, not the provided version. Have you found anything abnormal?

Nothing is abnormal. When I trained pi-gan on GRAF's CARLA dataset, I found the FID value was 26.17 at 50000 iter, but I used 5000 images to calculate the FID.
And if it's convenient, can you provide me with the models of pi-gan and GOF trained on GRAF's CARLA dataset?
Thanks a lot in advance.

**Comment by SheldonTsui** [comment]
Hi, @JJJLLLTTT The FID score is highly related to the number of testing images. Besides, the settings in the pi-GAN official code are quite different from those written in the paper so the exact FID score may be hard to recover. In my opinion, a fair comparison is acceptable. For the checkpoints, I can only find our model trained on CARLA now. Please refer to this link https://drive.google.com/drive/folders/1FTAzZkvXP0GapyIdh20mgYN-Kj5RoQHq?usp=sharing

**Comment by wasdzzzzzz** [comment]
> Hi, @JJJLLLTTT The FID score is highly related to the number of testing images. Besides, the settings in the pi-GAN official code are quite different from those written in the paper so the exact FID score may be hard to recover. In my opinion, a fair comparison is acceptable. For the checkpoints, I can only find our model trained on CARLA now. Please refer to this link https://drive.google.com/drive/folders/1FTAzZkvXP0GapyIdh20mgYN-Kj5RoQHq?usp=sharing

Thank you very much for your reply, which is very helpful to me~
