### ISSUE TITLE
Scripts of rendering mesh

### ISSUE THREAD

**Issue by MrTornado24** [SheldonTsui/GOF_NeurIPS2021#6]
Hi, thanks for releasing the code. I notice the script of rendering mesh only supports rotation on yaw. Could you please release scripts that also support rotation on the pitch, such as gif on your project page?

**Comment by SheldonTsui** [comment]
I shared it just now.

**Comment by MrTornado24** [comment]
@SheldonTsui Thanks for your quick reply!!
